### ISSUE TITLE
Issue 1- User can see their car.

### ISSUE THREAD

**Issue by dylandevei** [dylandevei/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] create necessary files in folder (HTML, CSS, JavaScript)
- [x] make sure to commit each step!!!
- [x] link css file to html file.
- [x] make background color green.
- [x] add the car to the display.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] fix all errors .
