### ISSUE TITLE
issue 2- user can turn their car

### ISSUE THREAD

**Issue by dylandevei** [dylandevei/driving-game#3]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] query select car image
- [x] create event listener for keydown event
- [x] make keydown event for car element
- [x] make it so car will rotate when user presses an arrow key
- [x] add transitions to car
- [x] remove all css styling that had no affect or was otherwise unnecessary  
- [x] fix all errors
