### ISSUE TITLE
Issue 3 - User can start their car

### ISSUE THREAD

**Issue by dylandevei** [dylandevei/driving-game#5]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] add a location to data model for car coordinates
- [x] apply absolute positioning to the car
- [x] create a setInterval to start the car and make it move
- [x] make position of car move once set interval begins
- [x] remove all css styling that had no affect or was otherwise unnecessary
- [x] fix all errors
